#!/usr/bin/env python

BROADCAST_ID = 0xFE  # 254
MAX_ID = 0xFC  # 252

# Control table address
STS_MODEL_NUMBER_L = 0
STS_MODEL_NUMBER_H = 1
STS_VERSION = 3
STS_ID = 5
STS_BAUD_RATE = 6
STS_RETURN_DELAY_TIME = 7
STS_RETURN_LEVEL = 8
STS_MIN_ANGLE_LIMIT_L = 9
STS_MIN_ANGLE_LIMIT_H = 10
STS_MAX_ANGLE_LIMIT_L = 11
STS_MAX_ANGLE_LIMIT_H = 12
STS_LIMIT_TEMPERATURE = 13
STS_MAX_LIMIT_VOLTAGE = 14
STS_MIN_LIMIT_VOLTAGE = 15
STS_MAX_TORQUE_L = 16
STS_MAX_TORQUE_H = 17
STS_ALARM_LED = 19
STS_ALARM_SHUTDOWN = 20
STS_COMPLIANCE_P = 21
STS_COMPLIANCE_D = 22
STS_COMPLIANCE_I = 23
STS_PUNCH_L = 24
STS_PUNCH_H = 25
STS_GOAL_POSITION_L = 30
STS_GOAL_POSITION_H = 31
STS_GOAL_TIME_L = 32
STS_GOAL_TIME_H = 33
STS_GOAL_SPEED_L = 34
STS_GOAL_SPEED_H = 35
STS_LOCK = 55

STS_PRESENT_POSITION_L = 38
STS_PRESENT_POSITION_H = 39
STS_PRESENT_SPEED_L = 40
STS_PRESENT_SPEED_H = 41
STS_PRESENT_LOAD_L = 42
STS_PRESENT_LOAD_H = 43
STS_PRESENT_VOLTAGE = 44
STS_PRESENT_TEMPERATURE = 45
STS_REGISTERED_INSTRUCTION = 47
STS_MOVING = 49
STS_LOCK = 55
STS_PUNCH_L = 50
STS_PUNCH_H = 51

# Protocol version
PROTOCOL_VERSION = 1.0

# Default setting
DEFAULT_ID = 1
DEFAULT_BAUDRATE = 1000000
DEFAULT_PROTOCOL = 1

# Instruction for STS Protocol
INST_PING = 1
INST_READ = 2
INST_WRITE = 3
INST_REG_WRITE = 4
INST_ACTION = 5
INST_RESET = 6
INST_SYNC_WRITE = 131

# Communication Result
COMM_SUCCESS = 0  # tx or rx packet communication success
COMM_PORT_BUSY = -1000  # Port is busy (in use)
COMM_TX_FAIL = -1001  # Failed transmit instruction packet
COMM_RX_FAIL = -1002  # Failed get status packet
COMM_TX_ERROR = -2000  # Incorrect instruction packet
COMM_RX_WAITING = -3000  # Now receiving status packet
COMM_RX_TIMEOUT = -3001  # There is no status packet
COMM_RX_CORRUPT = -3002  # Incorrect status packet
COMM_NOT_AVAILABLE = -9000  #
