controllers:
  res01:
    description: Venice Controller 01
    ip: 192.168.1.74
    last_seen: 1738471877.2202702
    mac: 2c:cf:67:8b:e6:c8

streams:
  venice_live:
    url: "https://www.youtube.com/live/HpZAez2oYsA?si=S5_605kITNMOowOG"
    description: "Venice Live Stream"
