controllers:
  tester:
    description: Test Controller
    ip: 192.168.1.106
    mac: a4:cf:99:57:e6:d2
    display:
      enabled: true
      show_camera: true
      show_plots: true
  res00:
    description: Reservoir Controller 00
    ip: 192.168.1.74
    last_seen: 1738471877.2202702
    mac: 2c:cf:67:8b:24:f6
    destination: res03
    display:
      enabled: true
      show_camera: true
      show_plots: true
  res01:
    description: Reservoir Controller 01
    ip: 192.168.1.178
    mac: 2c:cf:67:8c:50:b7
    destination: res00
    display:
      enabled: true
      show_camera: true
      show_plots: true
  res02:
    description: Reservoir Controller 02
    ip: 192.168.1.30
    mac: 2c:cf:67:8b:2b:d4
    destination: res00
    display:
      enabled: true
      show_camera: true
      show_plots: true
  res03:
    description: Reservoir Controller 03
    ip: 192.168.1.254
    mac: 2c:cf:67:8b:fe:ab
    destination: res00
    display:
      enabled: true
      show_camera: true
      show_plots: true
streams:
  venice_live:
    description: Venice Live Stream
    roi:
      cell_size: 40
      coordinates:
        height: 120
        width: 80
        x: 160
        y: 560
      selected_cells:
      - [5, 14]
      - [5, 15]
      - [4, 16]
      - [4, 15]
    training:
      end_time: '2025-02-09 21:08:07'
      last_update: '2025-02-09 21:08:07'
      metrics:
        accuracy: 1.0
        f1: 0.0
        precision: 0.0
        recall: 0.0
        test_size: 2
        train_size: 5
      start_time: '2025-02-09 21:07:04'
      total_frames: 2100
      updates_performed: 7
    url: https://www.youtube.com/live/HpZAez2oYsA?si=S5_605kITNMOowOG
