controllers:
  builder:
    description: Reservoir Builder
    destination: res00
    display:
      enabled: false
    ip: 192.168.1.133
    listen_port: 8777
    send_port: 8765
  output:
    description: Output Controller
    display:
      enabled: false
      show_camera: false
      show_plots: false
    ip: 192.168.0.108
    mac: 2c:cf:67:8b:24:f7
  res00:
    description: Reservoir Controller 00
    destination: res01
    display:
      enabled: true
      show_camera: true
      show_plots: true
    ip: 192.168.0.107
    listen_port: 8765
    mac: 2c:cf:67:8b:24:f6
    port: 8765
  res01:
    description: Reservoir Controller 01
    destination: res02
    display:
      enabled: true
      show_camera: true
      show_plots: true
    ip: 192.168.0.109
    mac: 2c:cf:67:8c:50:b7
    port: 8765
  res02:
    description: Reservoir Controller 02
    destination: res03
    display:
      enabled: true
      show_camera: true
      show_plots: true
    ip: 192.168.0.106
    mac: 2c:cf:67:8b:2b:d4
    port: 8765
  res03:
    description: Reservoir Controller 03
    destination: output
    display:
      enabled: true
      show_camera: true
      show_plots: true
    ip: 192.168.0.110
    mac: 2c:cf:67:8b:fe:ab
    port: 8765
  resX:
    description: Reservoir Controller X
    destination: output
    display:
      enabled: true
      show_camera: true
      show_plots: true
    ip: 192.168.0.11
    port: 8765
  trainer:
    description: Reservoir Trainer
    destination: builder
    display:
      enabled: false
    ip: 192.168.1.106
    listen_port: 8765
    send_port: 8777
servo_config:
  controllers:
    main:
      baud: 1000000
      debug: false
      port: /dev/ttyACM0
      servos:
        '1':
          id: 1
          last_position_deg: 0.0
          max_angle: 150.0
          min_angle: -150.0
          mode: servo
          name: servo_1
        '2':
          id: 2
          last_position_deg: 0.0
          max_angle: 150.0
          min_angle: -150.0
          mode: servo
          name: servo_2
        '3':
          id: 3
          last_position_deg: 0.0
          max_angle: 150.0
          min_angle: -150.0
          mode: servo
          name: servo_3
        '4':
          id: 4
          last_position_deg: 0.0
          max_angle: 150.0
          min_angle: -150.0
          mode: servo
          name: servo_4
        '5':
          id: 5
          last_position_deg: 0.0
          max_angle: 150.0
          min_angle: -150.0
          mode: servo
          name: servo_5
    secondary:
      baud: 1000000
      debug: false
      port: /dev/ttyACM1
      servos:
        '1':
          id: 1
          last_position_deg: 0.0
          max_angle: 150.0
          min_angle: -150.0
          mode: servo
          name: clock_servo
  debug: false
  default_accel: 50
  default_speed_ms: 1000
  save_positions: true
streams:
  venice_live:
    description: Venice Live Stream
    roi:
      cell_size: 40
      coordinates:
        height: 120
        width: 80
        x: 160
        y: 560
      selected_cells:
      - - 5
        - 14
      - - 5
        - 15
      - - 4
        - 16
      - - 4
        - 15
    training:
      end_time: '2025-02-09 21:08:07'
      last_update: '2025-02-09 21:08:07'
      metrics:
        accuracy: 1.0
        f1: 0.0
        precision: 0.0
        recall: 0.0
        test_size: 2
        train_size: 5
      start_time: '2025-02-09 21:07:04'
      total_frames: 2100
      updates_performed: 7
    url: https://www.youtube.com/live/HpZAez2oYsA?si=S5_605kITNMOowOG
video_input:
  destination: res00
  display:
    show_plots: true
  ip: 192.168.0.103
  listen_port: 8777
  output:
    csv_path: data/movement_vectors.csv
    plot_path: data/plots
  roi_configs:
    roi_1:
      description: ROI 1
      height: 120
      selected_cells:
      - - 3
        - 18
      - - 4
        - 18
      - - 4
        - 16
      - - 3
        - 16
      - - 3
        - 17
      - - 4
        - 17
      width: 80
      x: 120
      y: 640
    roi_2:
      description: ROI 2
      height: 120
      selected_cells:
      - - 25
        - 16
      - - 26
        - 16
      - - 27
        - 16
      - - 27
        - 17
      - - 26
        - 17
      - - 25
        - 17
      - - 25
        - 18
      - - 26
        - 18
      - - 27
        - 18
      width: 120
      x: 1000
      y: 640
    roi_3:
      description: ROI 3
      height: 120
      selected_cells:
      - - 22
        - 22
      - - 23
        - 22
      - - 24
        - 22
      - - 24
        - 23
      - - 22
        - 23
      - - 23
        - 23
      - - 23
        - 24
      - - 24
        - 24
      - - 22
        - 24
      width: 120
      x: 880
      y: 880
    roi_4:
      description: ROI 4
      height: 80
      selected_cells:
      - - 16
        - 13
      - - 17
        - 13
      - - 17
        - 12
      - - 16
        - 12
      width: 80
      x: 640
      y: 480
  sampling:
    frame_interval: 1
    save_interval: 60
    vector_interval: 30
    vector_size: 30
  send_port: 8765
  video_path: input_videos/ponte_morning20min.mp4
